name: 'venv setup'
description: 'configures venv, python and caches'

inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax."
  cache-dependency-path:
    description: "Requirement files to install. Can be a glob pattern."
    default: '**/requirements*.txt'
  venv-dir:
    default: '.venv'
  install-cmd:
    description: 'Command to install python dependencies.'

outputs:
  cache-hit:
    description: "A boolean value to indicate if a cache was restored"
    value: ${{ steps.cache-venv.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: thebrowsercompany/check-python-exists@ec632c598d7a818fdc195abb2d01b25b058126dc
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
        is-self-hosted: ${{ !startsWith(runner.name, 'GitHub Actions') }}

    - name: SHA the install command
      id: install-cmd-sha
      shell: bash
      # macOS doesn't include shasum256 and Windows doesn't include shasum, so
      # use python.
      run: |
        CMD_HASH="$(echo '${{ inputs.install-cmd }}' | python3 -c 'import hashlib,sys;print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())')"
        echo -n "install-cmd-sha=$CMD_HASH" >> $GITHUB_OUTPUT

    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      id: cache-venv
      with:
        path: ${{ inputs.venv-dir }}
        key: setup-venv-${{ runner.os }}-py-${{ steps.setup-python.outputs.python-version }}-${{ steps.setup-python.outputs.python-path }}-${{ hashFiles(inputs.cache-dependency-path) }}-${{ steps.install-cmd-sha.outputs.install-cmd-sha }}

    - run: python${{ steps.setup-python.outputs.python-version }} -m venv ${{ inputs.venv-dir }}
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash

    - name: venv save env (posix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        source ${{ inputs.venv-dir }}/bin/activate
        echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
        echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH

    - name: venv save env (windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        call ${{ inputs.venv-dir }}\\scripts\\activate
        echo "VIRTUAL_ENV=%VIRTUAL_ENV%" >> $GITHUB_ENV
        echo "%VIRTUAL_ENV%\scripts" >> $GITHUB_PATH

    - run: ${{ inputs.install-cmd }}
      if: inputs.install-cmd != '' && steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
